// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'context-translate-menuitem-history'
  | 'context-translate-menuitem-translate'
  | 'context-translate-paper-jobs-menu'
  | 'context-translate-paper-menu'
  | 'context-translate-prefs-auto-mode'
  | 'context-translate-prefs-glossary-export'
  | 'context-translate-prefs-glossary-import'
  | 'context-translate-prefs-glossary-title'
  | 'context-translate-prefs-llm-apikey'
  | 'context-translate-prefs-llm-baseurl'
  | 'context-translate-prefs-llm-model'
  | 'context-translate-prefs-llm-temperature'
  | 'context-translate-prefs-llm-title'
  | 'context-translate-prefs-target-language'
  | 'context-translate-prefs-translate-title'
  | 'context-translate-workbench-toolbar-button'
  | 'item-info-row-example-label'
  | 'item-section-example1-head-text'
  | 'item-section-example1-sidenav-tooltip'
  | 'item-section-example2-button-tooltip'
  | 'item-section-example2-head-text'
  | 'item-section-example2-sidenav-tooltip'
  | 'startup-begin'
  | 'startup-finish';
