// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "llm.baseUrl": string;
      "llm.apiKey": string;
      "llm.model": string;
      "llm.temperature": string;
      "llm.maxTokens": number;
      "llm.presets": string;
      "llm.activeIndex": number;
      "translate.sourceLanguage": string;
      "translate.targetLanguage": string;
      "translate.triggerMode": string;
      "translate.explicitActionsMigrated": boolean;
      "translate.wordLookupMode": string;
      "translate.autoMode": boolean;
      "paper.parser": string;
      "paper.template": string;
      "paper.mineruToken": string;
      "paper.mineruBaseURL": string;
      "paper.mineruModel": string;
      "paper.mineruOCR": boolean;
      "paper.concurrency": number;
      "paper.maxBatchCharacters": number;
      "paper.maxOutputTokens": number;
      "paper.privacyAccepted": boolean;
      "enable": boolean;
    };
  }
}
